name: Java CI/CD with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  JAVA_VERSION: 17

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        java-version: ${{ env.JAVA_VERSION }}
        distribution: 'temurin'
        cache: maven
    
    - name: Configure Maven Settings
      run: |
        mkdir -p ~/.m2
        echo '<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
          xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
          xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                              https://maven.apache.org/xds/settings-1.0.0.xsd">
          <mirrors>
            <mirror>
              <id>central</id>
              <name>Maven Central</name>
              <url>https://repo1.maven.org/maven2</url>
              <mirrorOf>*</mirrorOf>
            </mirror>
          </mirrors>
        </settings>' > ~/.m2/settings.xml
    
    - name: Build with Maven
      run: |
        mvn clean package \
        -Dmaven.wagon.http.ssl.insecure=true \
        -Dmaven.wagon.http.ssl.ignore.validity.dates=true
    
    - name: Run tests
      run: mvn test
